wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.31
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.10
    t:
      1:
      - 5
      2:
      - 5
      4: 3.9.10
      5: 0.10.31
      8:
      - 5
xtest:
  desc: null
  value: X_test_data.csv:v1
xtrain:
  desc: null
  value: X_train_data.csv:v1
ytest:
  desc: null
  value: y_train.npy:latest
ytrain:
  desc: null
  value: y_train.npy:latest
